#!/usr/bin/env python3
"""Build the ~/.claude.json explorer under claude-code-session/claude-json/.

One folder per object entry, recursively; every leaf is explained on its
parent's page. Content lives in claude-code-session/claude-json/_content.py
(a tree of dicts built with its N() and L() helpers); this script only
renders it. Each page is a self-contained static HTML file in the paper
style: inline CSS, no webfonts, one small inline script on pages that have a
key filter.

    python3 tools/build-claude-json-explorer.py

Generated pages carry GENERATED_MARK. A rebuild deletes marked pages that the
tree no longer produces and prunes the empty folders they leave; it never
touches files without the mark.
"""

from __future__ import annotations

import html
import importlib.util
import os
import re
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
POST_SLUG = "claude-code-session"
EXPLORER = "claude-json"
OUT_DIR = os.path.join(ROOT_DIR, POST_SLUG, EXPLORER)
CONTENT = os.path.join(OUT_DIR, "_content.py")
SITE = "https://quirq.ai"
GENERATED_MARK = "<!-- generated by tools/build-claude-json-explorer.py; edit claude-json/_content.py -->"

CSS = """
      :root {
        color-scheme: light;
        --paper: #ffffff;
        --paper-soft: #f7f7f5;
        --paper-warm: #fff8ea;
        --ink: #252525;
        --ink-soft: #4f4f4b;
        --ink-faint: #777772;
        --line: #deded9;
        --line-dark: #b8b8b1;
        --orange: #d98226;
        --orange-soft: #f7e3c8;
        --sans:
          -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
          Cantarell, "Helvetica Neue", Arial, sans-serif;
        --serif:
          "Iowan Old Style", "Palatino Linotype", "Book Antiqua", Palatino,
          Georgia, serif;
        --mono: "SFMono-Regular", Consolas, "Liberation Mono", monospace;
        --text: 704px;
        --page: 980px;
      }

      * { box-sizing: border-box; }

      body {
        margin: 0;
        color: var(--ink);
        background: var(--paper);
        font-family: var(--sans);
        font-size: 17px;
        line-height: 1.62;
        text-rendering: optimizeLegibility;
        -webkit-font-smoothing: antialiased;
      }

      a {
        color: inherit;
        text-decoration-color: rgba(37, 37, 37, 0.32);
        text-underline-offset: 0.18em;
      }

      a:hover { text-decoration-color: currentColor; }

      ::selection { color: var(--ink); background: #f7dcb8; }

      :focus-visible {
        outline: 3px solid rgba(217, 130, 38, 0.58);
        outline-offset: 3px;
      }

      .threadbar {
        display: flex;
        min-height: 58px;
        align-items: center;
        justify-content: space-between;
        gap: 24px;
        padding: 0 18px;
        border-bottom: 1px solid var(--line);
      }

      .thread-brand {
        display: inline-flex;
        align-items: center;
        gap: 12px;
        color: var(--ink);
        font-size: 14px;
        font-weight: 600;
        text-decoration: none;
      }

      .xo-logo { display: block; width: 34px; height: 34px; flex: 0 0 auto; }

      .thread-status {
        color: var(--ink-faint);
        font-family: var(--mono);
        font-size: 10px;
        letter-spacing: 0.07em;
        text-transform: uppercase;
        text-align: right;
      }

      .page {
        max-width: var(--page);
        margin: 0 auto;
        padding: 40px 22px 88px;
      }

      .crumbs ol {
        display: flex;
        flex-wrap: wrap;
        gap: 4px 0;
        margin: 0 0 34px;
        padding: 0;
        list-style: none;
        font-family: var(--mono);
        font-size: 12px;
        color: var(--ink-faint);
      }

      .crumbs li { overflow-wrap: anywhere; }
      .crumbs li + li::before { content: "/"; margin: 0 8px; color: var(--line-dark); }
      .crumbs a { color: var(--ink-faint); text-decoration: none; }
      .crumbs a:hover { color: var(--ink); text-decoration: underline; }
      .crumbs [aria-current] { color: var(--ink); }

      .kicker {
        display: flex;
        align-items: center;
        gap: 12px;
        margin: 0 0 18px;
        color: var(--orange);
        font-family: var(--mono);
        font-size: 11px;
        font-weight: 700;
        letter-spacing: 0.12em;
        text-transform: uppercase;
      }

      .kicker::before { width: 34px; height: 2px; background: currentColor; content: ""; }

      h1 {
        margin: 0 0 16px;
        font: 500 clamp(32px, 5vw, 50px) / 1.08 var(--serif);
        letter-spacing: -0.03em;
        overflow-wrap: anywhere;
      }

      h1 .key {
        font-family: var(--mono);
        font-size: 0.72em;
        font-weight: 500;
        letter-spacing: -0.02em;
      }

      .chips {
        display: flex;
        flex-wrap: wrap;
        gap: 8px;
        margin: 0 0 22px;
        padding: 0;
        list-style: none;
      }

      .chips li {
        padding: 2.5px 10px;
        border: 1px solid var(--line);
        border-radius: 999px;
        background: var(--paper-soft);
        color: var(--ink-soft);
        font-family: var(--mono);
        font-size: 11px;
        letter-spacing: 0.03em;
      }

      .lede {
        max-width: var(--text);
        margin: 0 0 1em;
        color: var(--ink-soft);
        font-family: var(--serif);
        font-size: clamp(18px, 2vw, 20px);
        line-height: 1.56;
      }

      .prose { max-width: var(--text); }
      .prose p { margin: 0 0 1.1em; }
      .prose ul, .prose ol { margin: 0 0 1.1em; padding-left: 1.3em; }
      .prose li { margin: 0.3em 0; }

      h2 {
        margin: 2.4em 0 0.6em;
        font: 600 clamp(22px, 2.8vw, 27px) / 1.2 var(--sans);
        letter-spacing: -0.022em;
        scroll-margin-top: 20px;
      }

      h2 .count {
        margin-left: 10px;
        color: var(--ink-faint);
        font-family: var(--mono);
        font-size: 0.5em;
        font-weight: 400;
        letter-spacing: 0.04em;
        vertical-align: 0.25em;
      }

      .group-intro { max-width: var(--text); margin: 0 0 14px; color: var(--ink-soft); font-size: 15.5px; }

      code {
        font-family: var(--mono);
        font-size: 0.86em;
        background: var(--paper-soft);
        border: 1px solid var(--line);
        border-radius: 4px;
        padding: 0.08em 0.35em;
        overflow-wrap: anywhere;
      }

      pre {
        overflow-x: auto;
        margin: 1.2em 0;
        padding: 16px 18px;
        border: 1px solid var(--line);
        border-radius: 8px;
        background: var(--paper-soft);
        font-family: var(--mono);
        font-size: 12.5px;
        line-height: 1.6;
        max-width: var(--text);
      }

      pre code { background: none; border: 0; padding: 0; white-space: pre; overflow-wrap: normal; }

      .toc {
        margin: 30px 0 0;
        padding: 20px 24px;
        border: 1px solid var(--line);
        border-radius: 10px;
        background: var(--paper-soft);
        max-width: var(--text);
      }

      .toc-title {
        margin: 0 0 10px;
        color: var(--ink-faint);
        font-family: var(--mono);
        font-size: 11px;
        font-weight: 700;
        letter-spacing: 0.12em;
        text-transform: uppercase;
      }

      .toc ol { margin: 0; padding: 0 0 0 1.4em; columns: 2; column-gap: 36px; font-size: 14.5px; line-height: 1.9; }
      .toc a { text-decoration: none; }
      .toc a:hover { text-decoration: underline; }

      .filter {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        gap: 10px 14px;
        margin: 26px 0 0;
        font-family: var(--mono);
        font-size: 12px;
        color: var(--ink-faint);
      }

      .filter input {
        width: min(100%, 320px);
        padding: 7px 10px;
        border: 1px solid var(--line-dark);
        border-radius: 6px;
        background: var(--paper);
        color: var(--ink);
        font: 14px var(--mono);
      }

      .table-wrap { margin: 0 0 8px; }

      table {
        width: 100%;
        border-collapse: collapse;
        font-size: 14.5px;
        line-height: 1.55;
      }

      th {
        text-align: left;
        padding: 9px 12px;
        border-bottom: 2px solid var(--line-dark);
        color: var(--ink-faint);
        font-family: var(--mono);
        font-size: 10.5px;
        font-weight: 700;
        letter-spacing: 0.08em;
        text-transform: uppercase;
        white-space: nowrap;
      }

      td {
        padding: 10px 12px;
        border-bottom: 1px solid var(--line);
        vertical-align: top;
      }

      tr:last-child td { border-bottom: 0; }
      tr:target td { background: var(--paper-warm); }

      td.k { width: 30%; }
      td.t { width: 13%; color: var(--ink-soft); font-family: var(--mono); font-size: 12px; }
      td.k code { font-size: 12.5px; background: none; border: 0; padding: 0; font-weight: 600; overflow-wrap: normal; word-break: normal; }
      td.k .ph { font-style: italic; font-weight: 500; color: var(--ink-soft); }
      td.k a.dir { text-decoration: none; }
      td.k a.dir code { text-decoration: underline; text-decoration-color: var(--orange); text-underline-offset: 0.2em; }
      td.k .slash { color: var(--orange); font-family: var(--mono); font-size: 12.5px; font-weight: 700; }
      td .pres { display: block; margin-top: 3px; color: var(--ink-faint); font-size: 11px; }
      td .note { margin-top: 5px; color: var(--ink-faint); font-size: 13px; }
      td .open { font-family: var(--mono); font-size: 11.5px; white-space: nowrap; }

      .src, .recon {
        display: inline-block;
        margin-left: 4px;
        padding: 1.5px 7px;
        border: 1px solid var(--line);
        border-radius: 999px;
        font-family: var(--mono);
        font-size: 9px;
        font-weight: 400;
        letter-spacing: 0.07em;
        text-transform: uppercase;
        white-space: nowrap;
        vertical-align: 2px;
      }
      .src { background: var(--paper-soft); color: var(--ink-faint); }
      .recon { background: var(--paper-warm); border-color: var(--orange-soft); color: #a8641a; }

      .callout {
        margin: 1.6em 0;
        padding: 16px 20px;
        border-left: 3px solid var(--orange);
        border-radius: 0 8px 8px 0;
        background: var(--paper-warm);
        max-width: var(--text);
        font-size: 15.5px;
      }
      .callout p { margin: 0 0 0.7em; }
      .callout p:last-child { margin-bottom: 0; }

      .tree {
        margin: 0;
        padding: 16px 20px;
        border: 1px solid var(--line);
        border-radius: 8px;
        background: var(--paper-soft);
        font-family: var(--mono);
        font-size: 12.5px;
        line-height: 1.75;
        max-width: var(--text);
      }
      .tree ul { margin: 0; padding-left: 20px; list-style: none; border-left: 1px solid var(--line); }
      .tree > ul { padding-left: 0; border-left: 0; }
      .tree li { overflow-wrap: anywhere; }
      .tree a { text-decoration: none; }
      .tree a:hover { text-decoration: underline; }
      .tree .ph { font-style: italic; color: var(--ink-soft); }
      .tree .sum { color: var(--ink-faint); font-family: var(--sans); font-size: 12.5px; }

      .page-foot {
        margin-top: 64px;
        padding-top: 18px;
        border-top: 1px solid var(--line);
        color: var(--ink-faint);
        font-size: 13.5px;
        max-width: var(--text);
      }
      .page-foot p { margin: 0 0 0.8em; }
      .page-foot nav { font-family: var(--mono); font-size: 12px; }
      .page-foot nav a { margin-right: 16px; }

      [hidden] { display: none !important; }

      @media (max-width: 640px) {
        .toc ol { columns: 1; }
        .thread-status { display: none; }
        table.keys, table.keys tbody, table.keys tr, table.keys td { display: block; width: auto; }
        table.keys thead { display: none; }
        table.keys tr { padding: 10px 0; border-bottom: 1px solid var(--line); }
        table.keys tr:last-child { border-bottom: 0; }
        table.keys td { padding: 2px 0; border: 0; }
        table.keys td.k, table.keys td.t { width: auto; }
        table.keys td.t { font-size: 11.5px; }
      }

      @media print {
        .threadbar, .filter { display: none !important; }
      }
"""

LOGO = """<svg class="xo-logo" viewBox="0 0 500 500" role="img" aria-label="XO">
          <polyline points="36.99 165.84 118.47 247.31 31.16 334.61" fill="none" stroke="#000" stroke-width="15.38"></polyline>
          <polyline points="328.12 165.06 246.65 246.53 333.95 333.84" fill="none" stroke="#83d63a" stroke-width="15.38"></polyline>
          <polyline points="380.51 165.06 461.99 246.53 374.68 333.84" fill="none" stroke="#83d63a" stroke-width="15.38"></polyline>
          <polyline points="244.91 165.84 163.44 247.31 250.74 334.61" fill="none" stroke="#000" stroke-width="15.38"></polyline>
        </svg>"""

FILTER_JS = """
    <script>
      (() => {
        "use strict";
        const input = document.getElementById("key-filter");
        const status = document.getElementById("key-filter-status");
        if (!input) return;
        const rows = Array.from(document.querySelectorAll("table.keys tbody tr"));
        const groups = Array.from(document.querySelectorAll("section.group"));
        const apply = () => {
          const q = input.value.trim().toLowerCase();
          let shown = 0;
          for (const row of rows) {
            const hit = !q || (row.dataset.key || "").toLowerCase().includes(q) ||
              row.textContent.toLowerCase().includes(q);
            row.hidden = !hit;
            if (hit) shown += 1;
          }
          for (const group of groups) {
            group.hidden = !group.querySelector("tbody tr:not([hidden])");
          }
          if (status) status.textContent = q ? `${shown} of ${rows.length} rows match` : "";
        };
        input.addEventListener("input", apply);
      })();
    </script>"""


def esc(s: str) -> str:
    return html.escape(s, quote=True)


def strip_tags(s: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", s))).strip()


def load_content():
    sys.dont_write_bytecode = True  # never leave __pycache__ inside the published folder
    spec = importlib.util.spec_from_file_location("claude_json_content", CONTENT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def children(node):
    """Child nodes (folders) in the order they appear in the node's groups."""
    out = []
    for g in node.get("groups", []):
        for r in g["rows"]:
            if r.get("node"):
                out.append(r)
    return out


def walk(node, trail=()):
    """Yield (node, trail) where trail is the tuple of ancestor nodes."""
    yield node, trail
    for child in children(node):
        yield from walk(child, trail + (node,))


def rel_folder(trail, node):
    parts = [n["folder"] for n in trail[1:]] + ([node["folder"]] if trail else [])
    return "/".join(parts)


def breakable(key: str) -> str:
    """Escape a key and add <wbr> at camelCase and _ boundaries, so long keys
    wrap between words instead of mid-word."""
    out = esc(key)
    out = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "<wbr>", out)
    out = out.replace("_", "_<wbr>")
    return out


def key_html(row):
    if row.get("placeholder"):
        return f'<code class="ph">&lt;{esc(row["key"])}&gt;</code>'
    return f"<code>{breakable(row['key'])}</code>"


def render_row(row):
    rid = "k-" + (row.get("folder") if row.get("node") else re.sub(r"[^A-Za-z0-9_-]+", "-", row["key"]))
    badge = row.get("badge")
    badge_html = ""
    if badge:
        cls = "recon" if badge in ("inferred", "partly inferred") else "src"
        badge_html = f' <span class="{cls}">{esc(badge)}</span>'
    pres = f'<span class="pres">{row["presence"]}</span>' if row.get("presence") else ""
    note = f'<div class="note">{row["notes"]}</div>' if row.get("notes") else ""
    if row.get("node"):
        href = row["folder"] + "/"
        key = (f'<a class="dir" href="{esc(href)}">{key_html(row)}<span class="slash">/</span></a>')
        meaning = f'{row["summary"]}{badge_html} <a class="open" href="{esc(href)}">open &rarr;</a>{note}'
    else:
        key = key_html(row)
        meaning = f"{row['meaning']}{badge_html}{note}"
    return (
        f'            <tr id="{esc(rid)}" data-key="{esc(row["key"])}">'
        f'<td class="k">{key}</td><td class="t">{esc(row["type"])}{pres}</td>'
        f"<td>{meaning}</td></tr>"
    )


def render_group(g, idx, with_ids):
    gid = g.get("id") or f"group-{idx}"
    n = len(g["rows"])
    noun = "row" if any(r.get("placeholder") for r in g["rows"]) else "key"
    head = f'{esc(g["title"])}<span class="count">{n} {noun if n == 1 else noun + "s"}</span>' if g.get("count", True) else esc(g["title"])
    intro = f'\n          <p class="group-intro">{g["intro"]}</p>' if g.get("intro") else ""
    rows = "\n".join(render_row(r) for r in g["rows"])
    col = g.get("key_col", "Key")
    return f"""
        <section class="group" id="{esc(gid)}" aria-labelledby="{esc(gid)}-h">
          <h2 id="{esc(gid)}-h">{head}</h2>{intro}
          <div class="table-wrap">
            <table class="keys">
              <thead><tr><th scope="col">{esc(col)}</th><th scope="col">Type</th><th scope="col">What it holds</th></tr></thead>
              <tbody>
{rows}
              </tbody>
            </table>
          </div>
        </section>"""


def render_tree(node, prefix):
    def rec(n, pre):
        items = []
        for c in children(n):
            href = pre + c["folder"] + "/"
            label = (f'<span class="ph">&lt;{esc(c["key"])}&gt;</span>' if c.get("placeholder") else esc(c["key"]))
            sub = rec(c, href)
            items.append(
                f'<li><a href="{esc(href)}">{label}/</a> <span class="sum">{esc(strip_tags(c.get("tree_label") or c["summary"]))}</span>{sub}</li>'
            )
        return f"<ul>{''.join(items)}</ul>" if items else ""
    return rec(node, prefix)


def page(node, trail, content):
    depth = len(trail)  # 0 for the explorer root
    up = "../" * depth
    to_post = up + "../"
    to_site = up + "../../"
    folder = rel_folder(trail, node)
    url = f"{SITE}/{POST_SLUG}/{EXPLORER}/" + (folder + "/" if folder else "")
    is_root = depth == 0

    # breadcrumbs
    crumbs = [f'<li><a href="{esc(to_post)}">{esc(content.POST_TITLE)}</a></li>']
    for i, anc in enumerate(trail):
        href = "../" * (depth - i)
        label = "~/.claude.json" if i == 0 else (f"&lt;{esc(anc['key'])}&gt;" if anc.get("placeholder") else esc(anc["key"]))
        crumbs.append(f'<li><a href="{esc(href)}">{label}</a></li>')
    here = "~/.claude.json" if is_root else (f"&lt;{esc(node['key'])}&gt;" if node.get("placeholder") else esc(node["key"]))
    crumbs.append(f'<li aria-current="page">{here}</li>')

    path_label = content.path_label(trail, node)
    title_text = node.get("title") or path_label
    h1 = node.get("h1") or f'<span class="key">{esc(path_label)}</span>'
    desc = strip_tags(node.get("description") or node.get("summary") or "")
    chips = "".join(f"<li>{c}</li>" for c in node.get("chips", []))
    chips_html = f'\n        <ul class="chips" aria-label="Facts">{chips}</ul>' if chips else ""
    lede = f'\n        <p class="lede">{node["lede"]}</p>' if node.get("lede") else ""

    blocks = []
    for b in node.get("before", []):
        bid = f' id="{esc(b["id"])}"' if b.get("id") else ""
        h = f'\n          <h2{bid}>{esc(b["title"])}</h2>' if b.get("title") else ""
        blocks.append(f'\n        <section class="prose">{h}\n          {b["html"]}\n        </section>')

    toc = ""
    if node.get("toc"):
        items = []
        for b in node.get("before", []):
            if b.get("id") and b.get("title"):
                items.append(f'<li><a href="#{esc(b["id"])}">{esc(b["title"])}</a></li>')
        for i, g in enumerate(node.get("groups", [])):
            gid = g.get("id") or f"group-{i}"
            items.append(f'<li><a href="#{esc(gid)}-h">{esc(g["title"])}</a></li>')
        for b in node.get("after", []):
            if b.get("id") and b.get("title"):
                items.append(f'<li><a href="#{esc(b["id"])}">{esc(b["title"])}</a></li>')
        toc = (
            '\n        <nav class="toc" aria-label="On this page">\n          <p class="toc-title">On this page</p>\n'
            f'          <ol>{"".join(items)}</ol>\n        </nav>'
        )

    filt = ""
    if node.get("filter"):
        filt = (
            '\n        <div class="filter" role="search">\n'
            '          <label for="key-filter">Filter rows</label>\n'
            '          <input id="key-filter" type="search" placeholder="key or word, e.g. trust" autocomplete="off" />\n'
            '          <span id="key-filter-status" aria-live="polite"></span>\n'
            "        </div>"
        )

    groups = "".join(render_group(g, i, True) for i, g in enumerate(node.get("groups", [])))

    after = []
    for b in node.get("after", []):
        bid = f' id="{esc(b["id"])}"' if b.get("id") else ""
        h = f'\n          <h2{bid}>{esc(b["title"])}</h2>' if b.get("title") else ""
        body = b["html"]
        if b.get("tree"):
            body = f'<div class="tree">{render_tree(node, "")}</div>'
        after.append(f'\n        <section class="prose">{h}\n          {body}\n        </section>')

    upnav = []
    if not is_root:
        upnav.append(f'<a href="../">&uarr; {esc("~/.claude.json" if depth == 1 else content.path_label(trail[:-1], trail[-1]))}</a>')
        if depth > 1:
            upnav.append(f'<a href="{esc(up)}">~/.claude.json</a>')
    upnav.append(f'<a href="{esc(to_post)}">{esc(content.POST_TITLE)}</a>')
    upnav.append(f'<a href="{esc(to_site)}">Writings</a>')

    script = FILTER_JS if node.get("filter") else ""
    return f"""<!doctype html>
{GENERATED_MARK}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="{esc(desc)}" />
    <meta name="author" content="Suraj Sharma" />
    <meta name="theme-color" content="#ffffff" />
    <link rel="icon" href="{esc(to_site)}assets/favicon.svg" />
    <link rel="canonical" href="{esc(url)}" />
    <meta property="og:title" content="{esc(title_text)}" />
    <meta property="og:description" content="{esc(desc)}" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="{esc(url)}" />
    <meta property="og:image" content="{SITE}/assets/og.jpg" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="{esc(title_text)}" />
    <meta name="twitter:description" content="{esc(desc)}" />
    <title>{esc(title_text)} · XO Research</title>
    <style>{CSS}    </style>
  </head>
  <body>
    <header class="threadbar">
      <a class="thread-brand" href="{esc(to_site)}" aria-label="Writings, home">
        {LOGO}
        <span>Writings</span>
      </a>
      <span class="thread-status">~/.claude.json, key by key</span>
    </header>
    <main class="page">
      <nav class="crumbs" aria-label="Breadcrumb"><ol>{"".join(crumbs)}</ol></nav>
      <header>
        <p class="kicker">{node.get("kicker") or content.KICKER}</p>
        <h1>{h1}</h1>{chips_html}{lede}
      </header>{toc}{"".join(blocks)}{filt}{groups}{"".join(after)}
      <footer class="page-foot">
        <p>{content.FOOTNOTE}</p>
        <nav aria-label="Up">{"".join(upnav)}</nav>
      </footer>
    </main>{script}
  </body>
</html>
"""


def main():
    content = load_content()
    root = content.ROOT
    written = set()
    for node, trail in walk(root):
        folder = rel_folder(trail, node)
        out_dir = os.path.join(OUT_DIR, folder) if folder else OUT_DIR
        os.makedirs(out_dir, exist_ok=True)
        path = os.path.join(out_dir, "index.html")
        text = page(node, trail, content)
        for ch in ("\u2014", "\u2013"):  # em and en dash, written as escapes
            if ch in text:
                i = text.index(ch)
                sys.exit(f"dash character in {path}: {text[max(0, i - 60):i + 20]!r}")
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        written.add(os.path.abspath(path))
    # delete stale generated pages, prune empty folders
    removed = 0
    for dirpath, dirnames, filenames in os.walk(OUT_DIR, topdown=False):
        for fn in filenames:
            p = os.path.abspath(os.path.join(dirpath, fn))
            if fn == "index.html" and p not in written:
                with open(p, encoding="utf-8") as f:
                    if GENERATED_MARK in f.read(400):
                        os.remove(p)
                        removed += 1
        if dirpath != OUT_DIR and not os.listdir(dirpath):
            os.rmdir(dirpath)
    print(f"wrote {len(written)} pages under {os.path.relpath(OUT_DIR, ROOT_DIR)}/, removed {removed} stale")


if __name__ == "__main__":
    main()
